name: Update release draft

on:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  drafterino-notes:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # full history with tags to get the version number by drafterino

      - name: Drafts the next release notes
        id: drafterino
        uses: enhantica/drafterino@develop
        with:
          config: |
            title: 'drafterino $COMPUTED_VERSION'
            tag: 'v$COMPUTED_VERSION'
            note-template: '- $PR_TITLE (#$PR_NUMBER)'

            default-bump: post

            major-bump-labels: ['[scope] significant']
            minor-bump-labels: ['[scope] enhancement']
            patch-bump-labels: ['[scope] bug', '[scope] maintenance']
            post-bump-labels: ['[scope] documentation']

            release-notes:
              - title: 'Added'
                labels: ['[scope] significant', '[scope] enhancement']
              - title: 'Fixed'
                labels: ['[scope] bug']
              - title: 'Changed'
                labels: ['[scope] maintenance', '[scope] documentation']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: ${{ steps.drafterino.outputs.tag_name }}
          name: ${{ steps.drafterino.outputs.release_name }}
          body: ${{ steps.drafterino.outputs.release_notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}