name: Update major tag pointer

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  update-major-tag:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update major version tag alias
        env:
          TAG_REF: ${{ github.ref_name }}
        run: |
          MAJOR_TAG=$(echo "$TAG_REF" | sed -E 's/^(v[0-9]+)\.[0-9]+\.[0-9]+$/\1/')
          echo "Updating $MAJOR_TAG to point to $TAG_REF"
          git tag -f "$MAJOR_TAG" "$TAG_REF"
          git push origin "$MAJOR_TAG" --force
